# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



hunt_red_october = Movie.create(title: 'The Hunt For Red October');

hunt_red_october_quiz_1 = hunt_red_october.quizzes.create(title: 'Hunt For Red October Quiz 1');


question_1 = hunt_red_october_quiz_1.questions.create(question_number: 1, question: "'The Hunt for Red October' is a movie about a submarine from what country?", answer_option_a: 'Canada', answer_option_b: 'China', answer_option_c: 'Germany', answer_option_d: 'Russia', correct_answer: 'Russia', answer_context: "It is of course about a Russian submarine, or as it was when the movie was released, a Soviet submarine, since the country was still called the Soviet Union.");
question_2 = hunt_red_october_quiz_1.questions.create(question_number: 2, question: "Which actor does NOT appear in 'The Hunt for Red October'?", answer_option_a: 'James Earl Jones', answer_option_b: 'Alec Baldwin', answer_option_c: 'Sean Connery', answer_option_d: 'Tommy Lee Jones', correct_answer: 'Tommy Lee Jones', answer_context: "James Earl Jones, the voice of Darth Vader, is of course in this movie, as are Sean Connery and Alec Baldwin. Jones and Baldwin are American, while Connery plays the Russian submarine captain"); 
question_3 = hunt_red_october_quiz_1.questions.create(question_number: 3, question: "When does the story in the movie take place?", answer_option_a: '1970s', answer_option_b: '1990s', answer_option_c: '1980s', answer_option_d: '1940s', correct_answer: '1980s', answer_context: "The movie plot takes place during 1984. Actual release of the film was not done until 1989, but since the movie was based upon a book, written by Tom Clancy, he wrote the story, which took place in 1984 in the book.");
question_4 = hunt_red_october_quiz_1.questions.create(question_number: 4, question: "One of the names of the United States' submarines in the movie was USS 'Dallas'. Is there a real submarine with this name?", answer_option_a: 'Yes', answer_option_b: 'No', answer_option_c: '', answer_option_d: '', correct_answer: 'Yes', answer_context: "The USS 'Dallas' is a real submarine."); 
question_5 = hunt_red_october_quiz_1.questions.create(question_number: 5, question: "In the movie, there is an area of underwater canyons that the submarine 'Red October' uses to hide in and head across the Atlantic ocean. What do the American's call this route?", answer_option_a: ' passage to the deep', answer_option_b: 'canyon ball run', answer_option_c: 'red route one', answer_option_d: 'the double peaks', correct_answer: 'red route one', answer_context: "The Americans aboard the USS 'Dallas' submarine call this passage Red Route One, and they know that the Russians have very accurate maps of this area, so they don't try to follow them in there."); 
question_6 = hunt_red_october_quiz_1.questions.create(question_number: 6, question: "What is the name of the secret drive aboard the 'Red October' submarine that allows them to run very quiet in the water?", answer_option_a: 'Secret Drive', answer_option_b: 'Caterpillar Drive', answer_option_c: 'Magneto-prop Drive', answer_option_d: 'Torpedo Drive', correct_answer: 'Caterpillar Drive', answer_context: "It was called a caterpillar drive, and it has no moving parts so it allows the submarine to move very quickly through the water."); 
question_7 = hunt_red_october_quiz_1.questions.create(question_number: 7, question: "What do the Americans say the secret drive of the 'Red October' would sound like if they could hear it with their sonar?", answer_option_a: 'Magma Bubbling', answer_option_b: 'Whales Humping', answer_option_c: 'Sonic Reverberation', answer_option_d: 'Fujito Magneto Holycowito', correct_answer: 'Whales Humping', answer_context: "Well they say it would sound like whales humping or some seismic anomaly; anything but a submarine. The computer on the USS 'Dallas' thinks it is a Magma Displacement, but the people never think that it is that."); 
question_8 = hunt_red_october_quiz_1.questions.create(question_number: 8, question: "Who was the captain of the submarine 'Red October'?", answer_option_a: 'Capt. Burt Mancuso', answer_option_b: 'Capt. Jack Ryan', answer_option_c: 'Capt. Vasili Borodin', answer_option_d: 'Capt. Marko Ramius', correct_answer: 'Capt. Marko Ramius', answer_context: "While all of the names were actual captains in the movie, except Dr. Jack Ryan, he is a Ph.D., not a captain. Capt. Mancuso was captain of the USS 'Dallas', and Capt. Borodin was actually second in command of the 'Red October'."); 
question_9 = hunt_red_october_quiz_1.questions.create(question_number: 9, question: "In the movie the American sonar man on the USS 'Dallas' refers to a 'crazy Ivan' while following the submarine 'Red October'. What is a 'crazy Ivan'?", answer_option_a: 'Depth charges in the water', answer_option_b: 'A sudden turn by a submarine', answer_option_c: 'Torpedo!', answer_option_d: 'The name of the chef on the submarine', correct_answer: 'A sudden turn by a submarine', answer_context: "It is of course meant to indicate that the Russian submarine has made a sudden, unexpected turn. It is done to check to see if anyone is behind the Russian submarine. The only way to avoid detection is to go dead silent and make like a hole in the water."); 
question_10 = hunt_red_october_quiz_1.questions.create(question_number: 10, question: "At the end of the movie 'The Hunt for Red October' where are the Americans trying to hide the submarine 'Red October'?", answer_option_a: 'Maine, USA', answer_option_b: 'Florida, USA', answer_option_c: 'Labrador, Canada', answer_option_d: 'Cuba', correct_answer: 'Maine, USA', answer_context: "They are trying to hide the submarine in a river in Maine so that the Russian satellites will not detect it, because it is not near any military bases."); 


